### ISSUE TITLE
Issue/conflict with new Xamarin.ios integration with Visual Studio

### ISSUE THREAD

**Issue by valdetero** [follesoe/VSMonoTouch#14]
In Visual Studio 2012, if you have VSMonoTouch and the new Xamarin.ios/Studio installed and try to open or create a new iOS project, it will constantly prompt you to change the TargetFramework version over and over. If you choose no, it loads the project just fine. If you open the properties for the project and manually change it to version v1.0, then Visual Studio goes into an endless loop and the process must be killed.

**Comment by follesoe** [comment]
Thanks for reporting. I am in the process of updating the extension to create an officiall build for VS2012. In the same time I will try to get any bugs sorted out - so will make sure this is fixed for the official VS2012 extension.

**Comment by valdetero** [comment]
No problem. At this point, is this extension still needed since now Xamarin "officially" supports visual studio?

**Comment by follesoe** [comment]
Only the bussines version support Visual Studio development, so for both Starter and Indie it could be usefull to have this extension. But (thankfully) it is not as usefull anymore.
