### ISSUE TITLE
Class Template should be registered into the new item dialog.

### ISSUE THREAD

**Issue by Lunat1k** [follesoe/VSMonoTouch#4]
I noticed that the class template is not available when adding a new item. I can create the file by hand and then include it into the project and it works just fine when I pull it into MonoDevelop.

Here is the documentation on how to register items to the add new item dialog. 
http://msdn.microsoft.com/en-us/library/bb165141.aspx

And more info here.
http://msdn.microsoft.com/en-us/library/bb165750.aspx

**Comment by follesoe** [comment]
Fixed in latest pull request.
