### ISSUE TITLE
Project won't load once migrated to MonoDevelop 2.8

### ISSUE THREAD

**Issue by Lunat1k** [follesoe/VSMonoTouch#6]
It appears that the Mono team has changed the project format. It will not load once you upgrade the project to MonoDevelop 2.8 format.

**Comment by Lunat1k** [comment]
After some investigation once you upgrade the ProjectTypeGuids will change

Old Value
<ProjectTypeGuids>{E613F3A2-FE9C-494F-B74E-F63BCB86FEA6};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>

New Value
<ProjectTypeGuids>{6BC8ED88-2882-458C-8E55-DFD12B67127B};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>

**Comment by follesoe** [comment]
Thanks for reporting. I will see if I can get around to updating VSMonoTouch to support MonoDevelop 2.8 projects over the weekend.

**Comment by Lunat1k** [comment]
Much Appreciated

**Comment by Lunat1k** [comment]
FYI I modified the code and have it working but I'm having problems commiting it to github to issue a pull request. Also for some reason it fixed issue #4. Maybe because I installed the SP1 SDK who knowns. I'll issue a pull request later today or tomorrow once I figure out why git is acting up.

**Comment by follesoe** [comment]
Fixed by Lunat1k
