### ISSUE TITLE
MonoDevelop 2.8 fix download update

### ISSUE THREAD

**Issue by Alphapage** [follesoe/VSMonoTouch#8]
Hello,

It would be nice to be able to download the last version of the vsix file installer which fixes the MonoDevelop 2.8 problem.
Could you tell me if you plan to upload this last version to install VSMonoTouch add in ?

For now, VS2010 sp1 can only load Wp7, MonoDroid projects : MonoTouch projects based on MonoDevelop 2.8 are unable to load.

Thanks in advance for your answer.

**Comment by follesoe** [comment]
I have built an official 1.2 release with support for MonoDevelop 2.8. It is available in the download section.

**Comment by Alphapage** [comment]
Thanks again. Great and fast work. Congratulations.

Just a little bug to fix depending on the new .xib file build action in MonoDevelop 2.8: it uses the build action "InterfaceDefinition" now instead of "Page" for .xib file. Here is the link:
http://monodevelop.com/Download/What%27s_new_in_MonoDevelop_2.8#InterfaceDefinition_Files

So, you can remove your DTE workaround:
http://stackoverflow.com/questions/6004928/visual-studio-2010-extensibility-override-build-action-without-effecting-cproj

The project will always use InterfaceDefinition from MonoDevelop 2.8 instead of Page and will never throw the warning: "Project file must include the .NET Framework assembly 'WindowsBase, PresentationCore, PresentationFramework' in the reference list".

Hope this will help you to improve the VSMonoTouch add in and you will be able to release a new add in to fix this problem soon.

Regards.
